version: "3.9"

services:
  db:
    image: postgres:15
    container_name: renteasy_db
    environment:
      POSTGRES_DB: renteasy
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d renteasy"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./Backend
    container_name: renteasy_backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/renteasy
      FLASK_ENV: development
    ports:
      - "5001:5000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./Backend:/app
    command: python app.py

volumes:
  postgres_data:
